name: wave_flutter
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.0.9
  rxdart: ^0.27.0
#  splashscreen: ^1.1.0
  flutter_native_splash: ^1.2.0
  shared_preferences: 2.0.5
  dio: 4.0.0
  fluttertoast: 8.0.6
  get_it: 7.1.3
  shimmer: ^2.0.0
  permission_handler: ^8.1.2
  image_picker: ^0.8.2
  syncfusion_flutter_charts: ^19.2.46+1
  flutter_svg: ^0.21.0
  lottie: ^1.1.0
  carousel_slider: ^4.0.0
  expandable: ^5.0.1
  http:
  xml2json: ^5.3.2
  xml:
  mask_text_input_formatter: ^2.3.0
  #flutter_masked_text: ^0.8.0
dev_dependencies:
  flutter_launcher_icons: ^0.9.2

flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/
    - assets/images/
    - assets/icons/
    - assets/animation/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
#        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
